/**
 * Easiest way to use images on any page:
 * 1. Put the image in public/images/ (e.g. public/images/necker.jpg)
 * 2. Add one line below: myImage: '/images/myImage.jpg',
 * 3. In any page: import { publicImages } from '@/app/lib/publicImages';
 *    Then use: <img src={publicImages.myImage} alt="..." /> or url('${publicImages.myImage}')
 * Root-relative paths (/images/...) work on all routes in dev and build.
 */
export const publicImages = {
  necker: '/images/necker.jpg',
  moskito: '/images/moskito.jpg',
  banner: '/images/banner_image.jpg',
  heroSlide1: '/images/hero-slide-1.jpg',
  heroSlide2: '/images/hero-slide-2.jpg',
  heroSlide3: '/images/hero-slide-3.jpg',
  eventLiveMusic: '/images/event-live-music.jpg',
  tennisActionBackhand: '/images/tennis-action-backhand.jpg',
  dinnerTableGuests: '/images/dinner-table-guests.jpg',
  dinnerWidePalms: '/images/dinner-wide-palms.jpg',
  tennisCourtPlayer: '/images/tennis-court-player.jpg',
  matchAnnouncer: '/images/match-announcer.jpg',
  proPortraitFila: '/images/pro-portrait-fila.jpg',
  groupPhotoCourt: '/images/group-photo-court.jpg',
  proPortraitSmile: '/images/pro-portrait-smile.jpg',
  dinnerBeachEvening: '/images/dinner-beach-evening.jpg',
  tennisActionBlue: '/images/tennis-action-blue.jpg',
  groupPhotoMoskito: '/images/group-photo-moskito.jpg',
  neckerOpenChampion: '/images/necker-open-champion.jpg',
  guitarPerformance: '/images/guitar-performance.jpg',
  islandDiningGuest: '/images/island-dining-guest.jpg',
  beachDockGroup: '/images/beach-dock-group.jpg',
  islandDog: '/images/island-dog.jpg',
  bransonBorgCelebrate: '/images/branson-borg-celebrate.jpg',
  islandGolfCourse: '/images/island-golf-course.jpg',
  bransonPianoGroup: '/images/branson-piano-group.jpg',
  singerGuitarStage: '/images/singer-guitar-stage.jpg',
  golfSwingOcean: '/images/golf-swing-ocean.jpg',
  trophyCeremonyCourt: '/images/trophy-ceremony-court.jpg',
  beachJumpFun: '/images/beach-jump-fun.jpg',
  bransonCourtsideMic: '/images/branson-courtside-mic.jpg',
  crowdPavilionCourt: '/images/crowd-pavilion-court.jpg',
  legendsMusicBand: '/images/legends-music-band.jpg',
  djLegendsMusic: '/images/dj-legends-music.jpg',
  borg: '/images/borg.jpg',
  rafa: '/images/rafa.jpg',
  kim: '/images/kim.jpg',
  novak: '/images/novak.jpg',
  bouchard: '/images/bouchard.jpg',
  vasek: '/images/vasek.jpg',
  seanpaul: '/images/seanpaul.jpg',
  johnmcenroe: '/images/johnmcenroe.jpg',
  jewel: '/images/jewel.jpg',
  tommyhaas: '/images/tommyhaas.jpg',
  donaldyoung: '/images/donaldyoung.jpg',
  martina: '/images/martina.jpg',
  bradgilbert: '/images/bradgilbert.jpg',
  mikebryan: '/images/mikebryan.jpg',
  kennychesney: '/images/kennychesney.jpg',
  kennyperforming: '/images/kennyperforming.jpg',
  bransonwinning: '/images/bransonwinning.jpg',
  samburns: '/images/samburns.jpg',
  carolinewozniacki: '/images/carolinewozniacki.jpg',
  neckerOpenGroup: '/images/neckeropen-group.jpg',
  redfoo: '/images/redfoo.jpg',
  rodlaver: '/images/rodlaver.jpg',
  floridageorgialine: '/images/floridageorgialine.jpg',
  jamiefoxx: '/images/jamiefoxx.jpg',
  kateupton: '/images/kateupton.jpg',
  chevychase: '/images/chevychase.jpg',
  bransonfun: '/images/bransonfun.jpg',
  mattkuchar: '/images/mattkuchar.jpg',
  gregnorman: '/images/gregnorman.jpg',
  tommyfleetwood: '/images/tommyfleetwood.jpg',
  brysondechambeau: '/images/brysondechambeau.jpg',
  jimmybuffett: '/images/jimmybuffett.jpg',
  kevinanderson: '/images/kevinanderson.jpg',
  borisbecker: '/images/borisbecker.jpg',
  juandelpotro: '/images/juandelpotro.jpg',
  stefanedberg: '/images/stefanedberg.jpg',
  nickkyrgios: '/images/nickkyrgios.jpg',
  dominicthiem: '/images/dominicthiem.jpg',
  andreabocelli: '/images/andreabocelli.jpg',
} as const;
